---
title: "Temperature Change and Carbon Dioxide"
execute:
  echo: false
  message: false
  warning: false
---
```{r}
#| message: FALSE
library(tidyverse)
library(janitor)
library(scales)
library(rstanarm)
```


```{r}
temp = read.csv("data/temperature_change.csv", fileEncoding="latin1") %>% clean_names()
carbon = read.csv("data/carbon_dioxide_emissions.csv") %>% clean_names()
methane = read.csv("data/methane_emissions.csv") %>% clean_names()
```

```{r}

temp2 = temp %>%
  select(area, months, element, y1990:y2018) %>%
  pivot_longer(cols = y1990:y2018,
               names_prefix = "y",
               names_to = "year",
               values_to = "value") %>%
  filter(element == "Temperature change") %>%
  rename("country"="area") %>%
  summarize("temperature_change" = sum(value), .by = c(country, year))

```

```{r}
carbon2 = carbon %>%
  select(country, x2018:x1990) %>%
  mutate(x1990 = na_if(x1990, "N/A")) %>%
  drop_na() %>%
  transform(x1990 = as.numeric(x1990)) %>%
  pivot_longer(cols = x1990:x2018,
               names_prefix = "x",
               names_to = "year",
               values_to = "carbon_dioxide_emissions") %>%
  arrange(country)
```

```{r}
methane2 = methane %>%
  select(country, x2018:x1990) %>%
  mutate(x1990 = na_if(x1990, "N/A")) %>%
  drop_na() %>%
  transform(x1990 = as.numeric(x1990)) %>%
  pivot_longer(cols = x1990:x2018,
               names_prefix = "x",
               names_to = "year",
               values_to = "methane_emissions") %>%
  arrange(country)
```

```{r}
joined = full_join(temp2, carbon2) |>
  filter(country != "World")
joined
```

``` {r}
# x <- joined |>
#   summarize("carbon_dioxide_emissions_sum" = sum(carbon_dioxide_emissions, na.rm = TRUE),
#             "temperature_change_sum" = sum(temperature_change, na.rm = TRUE),
#             .by=year)

x <- joined |>
  select(temperature_change, carbon_dioxide_emissions) |>
  drop_na()

x
```

``` {r}
fit_1 <- stan_glm(data = x, 
                    formula = temperature_change ~ 1, 
                    family = gaussian, 
                    refresh = 0,
                    seed = 9)
```

``` {r}
fit_1 |> 
  as_tibble()
```
```{r}
newobs = tibble(.rows = 1)
posterior_predict(fit_1, newdata = newobs) |>
  as_tibble() |>
  ggplot(aes(x = `1`)) +
  scale_y_continuous(labels = scales::percent_format()) +
  geom_histogram(aes(y = after_stat(count/sum(count))), bins = 100) +
  theme_classic() +
  labs(title = "Average Temperature Change From 1990 to 2018",
       subtitle = "Seems to be around 16-17 Celcius",
       x = "Temperature Change (Celcius)",
       y = "Percent")
```
```{r}
fit_2 <- stan_glm(data = x, 
                    formula = temperature_change ~ carbon_dioxide_emissions, 
                    family = gaussian, 
                    refresh = 0,
                    seed = 9)
x |>
  ggplot(aes(x = carbon_dioxide_emissions, y = temperature_change)) +
  geom_point(alpha = 0.3) +
  scale_x_log10() +
  geom_line(aes(y = fitted(fit_2))) +
  geom_smooth(method = lm)
```

